version: '3.8'

services:
  app:
    build: .
    command: bin/rails s -b 0.0.0.0 -p 8080
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: 'mysql2://mysql:3306/'
      REDIS_URL: 'redis://redis:6379/1'
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./tmp/mysql:/var/lib/mysql

  redis:
    image: redis:6.0

  prometheus:
    build:
      context: ./docker/prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'

volumes:
  prometheus-data:
